cargo-features = ["edition2024"]

[package]
name = "ambient-auction-interface"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "=0.9.2"
ambient-auction-api = { git = "https://github.com/ambient-xyz/auction-api", rev = "b363c4ed7a8d7f7b9dcdac4a1d23baf531a4beb6" }
five8_const = "1.0.0"

[features]
default = []
