cargo-features = ["edition2024"]

[package]
name = "ambient-auction-interface"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "=0.9.2"
ambient-auction-api = { git = "https://github.com/ambient-xyz/auction-api", rev = "45d2dfc029ccd0fce0f3daa672328e32a5e0e8aa" }
five8_const = "1.0.0"

[features]
default = []
